# Generated by Django 6.0 on 2025-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='카드명')),
                ('image', models.ImageField(upload_to='cards/', verbose_name='카드 이미지')),
                ('condition', models.CharField(choices=[('S', 'S급'), ('A', 'A급'), ('B', 'B급'), ('C', 'C급')], max_length=1, verbose_name='상태')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='판매 가격')),
                ('sale_status', models.CharField(choices=[('available', '판매중'), ('sold', '판매완료')], default='available', max_length=10, verbose_name='판매 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카드',
                'verbose_name_plural': '카드들',
                'ordering': ['-created_at'],
            },
        ),
    ]
