# Generated by Django 6.0 on 2025-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sale_status',
            field=models.CharField(choices=[('available', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='available', max_length=10, verbose_name='판매 상태'),
        ),
    ]
