# Generated by Django 6.0 on 2025-12-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('N', '노멀(N)'), ('R', '레어(R)'), ('SR', '슈퍼 레어(SR)'), ('UR', '울트라 레어(UR)'), ('SE', '시크릿 레어(SE)'), ('UL', '얼티미트 레어(UL)'), ('HR', '홀로그래픽 레어(HR)')], default='N', max_length=2, verbose_name='레어리티'),
        ),
    ]
