# Generated by Django 6.0 on 2025-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='cards/optimized/', verbose_name='최적화된 이미지'),
        ),
    ]
