# Generated by Django 6.0 on 2025-12-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_image_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카드 시리얼'),
        ),
    ]
