# Generated by Django 6.0 on 2025-12-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='카드명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '카드명',
                'verbose_name_plural': '카드명들',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='cards_cardn_name_56f824_idx')],
            },
        ),
    ]
